services:
    brille24_tier_price.fixture.tier_price:
        class: Brille24\SyliusTierPricePlugin\Fixture\TierPriceFixture
        arguments: ['@doctrine.orm.default_entity_manager', '@brille24_tier_price.fixture.example_factory.tier_price']
        tags:
            - { name: sylius_fixtures.fixture }
