imports:
  - { resource: "services.xml" }
  - { resource: "resources.yml" }

sylius_ui:
  events:
    sylius.admin.product_variant.update.javascripts:
      blocks:
        brille24_tierprice_plugin_product_variant:
          template: '@Brille24SyliusTierPricePlugin/Admin/_javascripts.html.twig'
    sylius.admin.product.update.javascripts:
      blocks:
        brille24_tierprice_plugin_product_variant:
          template: '@Brille24SyliusTierPricePlugin/Admin/_javascripts.html.twig'
    sylius.shop.layout.javascripts:
      blocks:
        brille24_tierprice_plugin_add_tierpricing_calculation_to_shop:
          template: '@Brille24SyliusTierPricePlugin/Shop/_javascripts.html.twig'
    sylius.shop.product.show.before_add_to_cart:
      blocks:
        brille24_tierprice_plugin_add_tierprice_table_to_product_view:
          template: '@Brille24SyliusTierPricePlugin/Shop/Product/Show/_tier_price_promo.html.twig'
