imports:
    - { resource: "app/twig_hooks/**/*.yaml" }

# New resources
sylius_resource:
  resources:
    brille24.tierprice:
      classes:
        model: Brille24\SyliusTierPricePlugin\Entity\TierPrice
        form: Brille24\SyliusTierPricePlugin\Form\TierPriceType
        repository: Brille24\SyliusTierPricePlugin\Repository\TierPriceRepository
#        factory: Brille24\SyliusTierPricePlugin\Factory\TierPriceFactory


