sylius_twig_hooks:
    hooks:
        sylius_shop.product.show.content.info.summary.prices:
            brille24_tierprice:
                priority: -100
                template: '@Brille24SyliusTierPricePlugin/Shop/Product/Show/_tier_price_promo.html.twig'
